src/MyTransactions/Controllers/BankAccountController.cs
using Magrathea.Interfaces;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyTransactions.Core.DomainModels;
using MyTransactions.Core.DomainQueries;

namespace MyTransactions.Controllers
{
    [Authorize]
    public class BankAccountController : Controller
    {
        private readonly IRepository _repository;

        public BankAccountController(IRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            var query = new BankAccountsByUserIdQuery(User.Identity.GetUserId());
            var myAccounts = _repository.Find(query);

            return View(myAccounts);
        }

        public ActionResult Create()
        {
            return View(new BankAccount());
        }

        [HttpPost]
        public ActionResult Create(BankAccount account)
        {
            account.UserId = User.Identity.GetUserId();

            _repository.Context.Add(account);
            _repository.Context.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var query = new BankAccountByIdQuery(id);
            var account = _repository.Find(query);

            _repository.Context.Remove(account);
            _repository.Context.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var query = new BankAccountByIdQuery(id);
            var account = _repository.Find(query);

            return View(account);
        }
    }
}

src/MyTransactions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Transactions</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accounts", "Index", "BankAccount")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Transactions</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>