src/MyTransactions/Models/TransactionViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using MyTransactions.Core.DomainModels;

namespace MyTransactions.Models
{
    public class TransactionIndexViewModel
    {
        public BankAccountViewModel Account { get; set; }
        public BankTransactionViewModel NewTransaction { get; set; }
        public List<SelectListItem>TransactionTypeSelectListItems { get; set; }
    }

    public class TransactionIndexViewModelBuilder
    {
        public TransactionIndexViewModel Build(BankAccount account)
        {
            var viewModel = new TransactionIndexViewModel
            {
                Account = BuildAccountViewModel(account),
                NewTransaction = new BankTransactionViewModel
                {
                    BankAccountId = account.Id,
                    Date = DateTime.Now.ToShortDateString()
                },
                TransactionTypeSelectListItems = GetTransactionTypeSelectListItems()
            };


            return viewModel;
        }

        private BankAccountViewModel BuildAccountViewModel(BankAccount account)
        {
            var model = new BankAccountViewModel
            {
                Id = account.Id,
                Name = account.Name,
                StartingBalance = account.StartingBalance,
                CurrentBalance = account.CurrentBalance,
                Transactions = BuildTransactionsViewModels(account.Transactions, account.StartingBalance)
            };

            return model;
        }

        private static IEnumerable<BankTransactionViewModel> BuildTransactionsViewModels(IEnumerable<BankTransaction> accountTransactions, decimal accountCurrentBalance)
        {
            var transactionsSorted = accountTransactions.OrderBy(x => x.PostedDate).ToList();

            var models = new List<BankTransactionViewModel>();
            foreach (var transaction in transactionsSorted)
            {
                if (transaction.TransactionType == BankTransactionType.Credit)
                    accountCurrentBalance += transaction.Amount;
                else
                    accountCurrentBalance -= transaction.Amount;

                var model = new BankTransactionViewModel
                {
                   BankAccountId = transaction.BankAccount.Id,
                   TransactionType = Enum.GetName(typeof(BankTransactionType), transaction.TransactionType),
                   Id = transaction.Id,
                   CheckNumber = transaction.CheckNumber,
                   Amount = transaction.Amount,
                   Description = transaction.Description,
                   Date = transaction.PostedDate.ToShortDateString(),
                   Cleared = transaction.Cleared,
                   Memo = transaction.Memo,
                   Balance = accountCurrentBalance
                };

                models.Add(model);
            }

            return models.AsEnumerable();
        }

        private List<SelectListItem> GetTransactionTypeSelectListItems()
        {
            var items = new List<SelectListItem>();
            var values = Enum.GetValues(typeof(BankTransactionType));

            foreach (var value in values)
            {
                items.Add(new SelectListItem
                {
                    Value = value.ToString(),
                    Text = Enum.GetName(typeof(BankTransactionType), value)
                });
            }

            return items;
        }
    }

    public class BankAccountViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal StartingBalance { get; set; }
        public decimal CurrentBalance { get; set; }
        public IEnumerable<BankTransactionViewModel> Transactions { get; set; }
    }

    public class BankTransactionViewModel
    {
        public int BankAccountId { get; set; }

        public int Id { get; set; }

        [Required]
        public string Date { get; set; }

        public int? CheckNumber { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public string Description { get; set; }

        [Required]
        public string TransactionType { get; set; }

        [Required]
        public decimal Amount { get; set; }

        public bool Cleared { get; set; }

        public string Memo { get; set; }

        public decimal Balance { get; set; }
        
    }
}

src/MyTransactions/Controllers/TransactionController.cs
using System;
using System.Web.Mvc;
using Magrathea.Interfaces;
using MyTransactions.Core.DomainModels;
using MyTransactions.Core.DomainQueries;
using MyTransactions.Models;

namespace MyTransactions.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly IRepository _repository;

        public TransactionController(IRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index(int id)
        {
            var query = new BankAccountByIdQuery(id);
            var account = _repository.Find(query);

            var model = new TransactionIndexViewModelBuilder().Build(account);

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(TransactionIndexViewModel model)
        {
            var query = new BankAccountByIdQuery(model.NewTransaction.BankAccountId);
            var account = _repository.Find(query);

            var newTransaction = new BankTransaction
            {
                PostedDate = DateTime.Parse(model.NewTransaction.Date),
                CheckNumber = model.NewTransaction.CheckNumber,
                Amount = model.NewTransaction.Amount,
                Cleared = model.NewTransaction.Cleared,
                Description = model.NewTransaction.Description,
                Memo = model.NewTransaction.Memo,
                TransactionType =
                    (BankTransactionType)
                    Enum.Parse(typeof(BankTransactionType), model.NewTransaction.TransactionType)
            };

            account.Transactions.Add(newTransaction);
            _repository.Context.Commit();

            return RedirectToAction("Index");
        }

        [Authorize]
        public JsonResult SetCleared(int transactionId, bool isCleared)
        {
            var query = new BankTransactionByIdQuery(transactionId);
            var transaction = _repository.Find(query);

            transaction.Cleared = isCleared;
            _repository.Context.Commit();

            return Json("Success");
        }
    }
}

src/MyTransactions/Views/Transaction/Index.cshtml
@model MyTransactions.Models.TransactionIndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>@Html.DisplayFor(model => model.Account.Name)</h2>

<div>
    <table class="table">
        <tr>
            <th>
                Cleared
            </th>
            <th>
                Date
            </th>
            <th>
                Number
            </th>
            <th>
                Type
            </th>
            <th>
                Description
            </th>
            <th>
                Memo
            </th>
            <th>
                Amount
            </th>
            <th>
                @Html.DisplayFor(model => model.Account.StartingBalance)
            </th>
        </tr>
        <tr>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.NewTransaction.BankAccountId)
                <td>
                    <div class="checkbox">
                        @Html.EditorFor(model => model.NewTransaction.Cleared)
                        @Html.ValidationMessageFor(model => model.NewTransaction.Cleared, "", new { @class = "text-danger" })
                    </div>
                </td>
                <td class="col-xs-2">
                    @Html.EditorFor(model => model.NewTransaction.Date, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td class="col-xs-1">@Html.EditorFor(model => model.NewTransaction.CheckNumber, new { htmlAttributes = new { @class = "form-control", size = "3" } })</td>
                <td style="z-index: 10">@Html.DropDownListFor(model => model.NewTransaction.TransactionType, Model.TransactionTypeSelectListItems, new { @class = "form-control" })</td>
                <td>@Html.EditorFor(model => model.NewTransaction.Description, new { htmlAttributes = new { @class = "form-control" } })</td>
                <td>@Html.EditorFor(model => model.NewTransaction.Memo, new { htmlAttributes = new { @class = "form-control" } })</td>
                <td>@Html.EditorFor(model => model.NewTransaction.Amount, new { htmlAttributes = new { @class = "form-control", size = "1", @style = "text-align: right;" } })</td>
                <td><input type="submit" value="Add" class="btn btn-default" /></td>
            }
        </tr>

        @foreach (var item in Model.Account.Transactions)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.Id)
                    @Html.EditorFor(modelItem => item.Cleared, new { htmlAttributes = new { @class = ".checkAll", itemId = item.Id } })
                </td>
                <td>
                    @item.Date
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CheckNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransactionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Memo)
                </td>
                <td style="text-align: right">
                    $ @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td style="text-align: right">
                    $ @Html.DisplayFor(modelItem => item.Balance)
                </td>
            </tr>
        }
    </table>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            var date = new Date();
            var currentDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());

            $('#NewTransaction_Date').datepicker({
                autoclose: true
            });

            $('input[type="checkbox"]').click(function () {

                var transactionId = parseInt($(this).attr('itemId'));
                var isCleared = this.checked;
                var jsonObject = { 'transactionId': transactionId, 'isCleared': isCleared };

                $.ajax({
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    url: '@Url.Action("SetCleared", "Transaction")',
                    data: JSON.stringify(jsonObject),
                    dataType: 'json',
                    async: true
                });
            });

        });
    </script>
}